# Generated by Django 4.2.8 on 2023-12-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='staff/workers_photos', verbose_name='Фото работника')),
                ('ordering', models.FloatField(default=42, verbose_name='Показан(а) на странице')),
                ('academic_rank', models.CharField(max_length=100, verbose_name='Учёное звание')),
                ('position', models.CharField(blank=True, max_length=150, null=True, verbose_name='Должность в институте')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рабочая почта')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адресс')),
                ('google_academy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google academy')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_finishing', models.IntegerField(verbose_name='Год окончания')),
                ('sudy_description', models.CharField(max_length=300, verbose_name='Информация')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.worker')),
            ],
            options={
                'verbose_name': 'Сотрудник: образование',
                'verbose_name_plural': 'Сотрудники: образование',
                'ordering': ['worker', 'study_finishing'],
            },
        ),
    ]
