# Generated by Django 4.2.8 on 2023-12-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='sudy_description',
            new_name='study_description',
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_start', models.IntegerField(verbose_name='Начало карьерного этапа')),
                ('career_period', models.CharField(max_length=30, verbose_name='Период работы')),
                ('career_description', models.CharField(max_length=300, verbose_name='Информация о работе')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.worker')),
            ],
            options={
                'verbose_name': 'Сотрудник: карьера',
                'verbose_name_plural': 'Сотрудники: карьера',
                'ordering': ['worker', 'career_start'],
            },
        ),
    ]
