# Generated by Django 4.2.8 on 2023-12-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_rename_sudy_description_education_study_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('', models.IntegerField(verbose_name='Год')),
                ('reward_description', models.CharField(max_length=300, verbose_name='Информация о награде')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.worker')),
            ],
            options={
                'verbose_name': 'Сотрудник: награды',
                'verbose_name_plural': 'Сотрудники: награды',
                'ordering': ['worker', ''],
            },
        ),
    ]
