# Generated by Django 4.2.8 on 2023-12-16 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science_interest', models.CharField(max_length=300, verbose_name='Информация о награде')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.worker')),
            ],
            options={
                'verbose_name': 'Сотрудник: научные интересы',
                'verbose_name_plural': 'Сотрудники: научные интересы',
                'ordering': ['worker', 'id'],
            },
        ),
    ]
