# Generated by Django 4.2.8 on 2023-12-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_scienceinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['-ordering'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='education',
            name='study_description',
            field=models.CharField(max_length=300, verbose_name='Информация об образовании'),
        ),
        migrations.AlterField(
            model_name='scienceinterest',
            name='science_interest',
            field=models.CharField(max_length=300, verbose_name='Научные интересы'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_year', models.IntegerField(verbose_name='Год публикации')),
                ('publication_description', models.TextField(max_length=600, verbose_name='Публикация')),
                ('publication_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на публикацию')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.worker')),
            ],
            options={
                'verbose_name': 'Сотрудник: публикации',
                'verbose_name_plural': 'Сотрудники: публикации',
                'ordering': ['worker', '-publication_year'],
            },
        ),
    ]
