# Generated by Django 4.2.8 on 2023-12-27 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['device', '-time_creation'], 'verbose_name': 'Галерея прибора', 'verbose_name_plural': 'Галереи приборов'},
        ),
        migrations.AlterField(
            model_name='devices',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Предназначение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main_app.devices', verbose_name='Прибор'),
        ),
        migrations.AlterField(
            model_name='techcharacteristic',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='main_app.devices', verbose_name='Прибор'),
        ),
    ]
