# Generated by Django 4.2.8 on 2023-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='time_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в БД'),
        ),
    ]
