# Generated by Django 4.2.8 on 2023-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_devices_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=455, null=True, verbose_name='Описание')),
                ('document', models.ImageField(upload_to='main/ddocuments', verbose_name='Файл документа')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-time_creation'],
            },
        ),
    ]
