# Generated by Django 4.2.8 on 2023-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='main/ddocuments', verbose_name='Файл документа'),
        ),
    ]
