# Generated by Django 4.2.8 on 2023-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='main/documents', verbose_name='Файл документа'),
        ),
    ]
