# Generated by Django 4.2.8 on 2023-12-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('report_file', models.FileField(upload_to='observations/reports', verbose_name='Файл отчёта')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Годовой отчёт',
                'verbose_name_plural': 'Годовые отчёты',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='DailyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(verbose_name='Дата')),
                ('weekday_field', models.CharField(max_length=9, verbose_name='День недели')),
                ('common_ozone', models.FloatField(blank=True, null=True, verbose_name='Общее содержание озона, единицы Добсона')),
                ('ultraviolet_index', models.FloatField(blank=True, null=True, verbose_name='УФ индекс')),
                ('ultraviolet_max', models.FloatField(blank=True, null=True, verbose_name='УФ макс. ')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Измерение',
                'verbose_name_plural': 'Измерения',
                'ordering': ['-date_field'],
            },
        ),
    ]
