# Generated by Django 4.2.8 on 2024-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonOzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(verbose_name='Дата')),
                ('minsk_station', models.FloatField(blank=True, null=True, verbose_name='Минск')),
                ('homel_station', models.FloatField(blank=True, null=True, verbose_name='Гомель')),
                ('naroch_station', models.FloatField(blank=True, null=True, verbose_name='Нарочь')),
            ],
            options={
                'verbose_name': 'ОСО, ед. Добсона',
                'verbose_name_plural': 'ОСО, ед. Добсона',
                'ordering': ['-date_field'],
            },
        ),
        migrations.CreateModel(
            name='GroundOzone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(verbose_name='Дата')),
                ('minsk_station', models.FloatField(blank=True, null=True, verbose_name='Минск')),
                ('homel_station', models.FloatField(blank=True, null=True, verbose_name='Гомель')),
                ('naroch_station', models.FloatField(blank=True, null=True, verbose_name='Нарочь')),
            ],
            options={
                'verbose_name': 'Приземный озон, ед. ???',
                'verbose_name_plural': 'Приземный озон, ед. ???',
                'ordering': ['-date_field'],
            },
        ),
        migrations.CreateModel(
            name='UltravioletIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_field', models.DateField(verbose_name='Дата')),
                ('minsk_station', models.FloatField(blank=True, null=True, verbose_name='Минск')),
                ('homel_station', models.FloatField(blank=True, null=True, verbose_name='Гомель')),
                ('naroch_station', models.FloatField(blank=True, null=True, verbose_name='Нарочь')),
            ],
            options={
                'verbose_name': 'УФ-индекс, ед. ???',
                'verbose_name_plural': 'УФ-индекс, ед. ???',
                'ordering': ['-date_field'],
            },
        ),
        migrations.DeleteModel(
            name='DailyMeasure',
        ),
    ]
