# Generated by Django 4.2.8 on 2024-01-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_commonozone_groundozone_ultravioletindex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonozone',
            options={'ordering': ['-date_field'], 'verbose_name': 'Измерение ОСО', 'verbose_name_plural': 'Измерения ОСО'},
        ),
        migrations.AlterModelOptions(
            name='groundozone',
            options={'ordering': ['-date_field'], 'verbose_name': 'Измерение Приземного озона', 'verbose_name_plural': 'Измерения Приземного озона'},
        ),
        migrations.AlterModelOptions(
            name='ultravioletindex',
            options={'ordering': ['-date_field'], 'verbose_name': 'Измерение УФ-индекса', 'verbose_name_plural': 'Измерения УФ-индекса'},
        ),
    ]
