# Generated by Django 4.2.8 on 2024-01-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_alter_commonozone_options_alter_groundozone_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('common_ozone_minsk', models.FloatField(blank=True, null=True, verbose_name='ОСО Минск')),
                ('common_ozone_homel', models.FloatField(blank=True, null=True, verbose_name='ОСО Гомель')),
                ('common_ozone_naroch', models.FloatField(blank=True, null=True, verbose_name='ОСО Нарочь')),
                ('ground_ozone_minsk', models.FloatField(blank=True, null=True, verbose_name='ПСО Минск')),
                ('ground_ozone_homel', models.FloatField(blank=True, null=True, verbose_name='ПСО Гомель')),
                ('ground_ozone_naroch', models.FloatField(blank=True, null=True, verbose_name='ПСО Нарочь')),
                ('uf_index_minsk', models.FloatField(blank=True, null=True, verbose_name='УФ Минск')),
                ('uf_index_homel', models.FloatField(blank=True, null=True, verbose_name='УФ Гомель')),
                ('uf_index_naroch', models.FloatField(blank=True, null=True, verbose_name='УФ Нарочь')),
            ],
            options={
                'verbose_name': 'Измерени',
                'verbose_name_plural': 'Измерения УФ-индекса',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='CommonOzone',
        ),
        migrations.DeleteModel(
            name='GroundOzone',
        ),
        migrations.DeleteModel(
            name='UltravioletIndex',
        ),
    ]
