# Generated by Django 4.2.8 on 2024-02-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_allobservations_delete_commonozone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observations',
            options={'ordering': ['-date'], 'verbose_name': 'Наблюдение', 'verbose_name_plural': 'Наблюдения'},
        ),
    ]
