# Generated by Django 4.2.8 on 2024-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_alter_observations_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observations',
            name='ground_ozone_homel',
        ),
        migrations.RemoveField(
            model_name='observations',
            name='ground_ozone_naroch',
        ),
        migrations.AddField(
            model_name='observations',
            name='uf_max_homel',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-макс Гомель'),
        ),
        migrations.AddField(
            model_name='observations',
            name='uf_max_minsk',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-макс Минск'),
        ),
        migrations.AddField(
            model_name='observations',
            name='uf_max_naroch',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-макс Нарочь'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='date',
            field=models.DateField(unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='uf_index_homel',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-индекс Гомель'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='uf_index_minsk',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-индекс Минск'),
        ),
        migrations.AlterField(
            model_name='observations',
            name='uf_index_naroch',
            field=models.FloatField(blank=True, null=True, verbose_name='УФ-индекс Нарочь'),
        ),
    ]
