# Generated by Django 4.2.8 on 2024-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_remove_observations_ground_ozone_homel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observations',
            name='id',
        ),
        migrations.AlterField(
            model_name='observations',
            name='date',
            field=models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Дата'),
        ),
    ]
