# Generated by Django 4.2.8 on 2024-04-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_remove_observations_id_alter_observations_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnualReport',
        ),
    ]
