# Generated by Django 4.2.8 on 2024-05-18 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_delete_annualreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observations',
            old_name='ground_ozone_minsk',
            new_name='surface_ozone_minsk',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uf_index_homel',
            new_name='uvi_homel',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uf_max_homel',
            new_name='uvi_max_homel',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uf_max_minsk',
            new_name='uvi_max_minsk',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uf_max_naroch',
            new_name='uvi_max_naroch',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uf_index_minsk',
            new_name='uvi_minsk',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uf_index_naroch',
            new_name='uvi_naroch',
        ),
    ]
