# Generated by Django 4.2.8 on 2025-06-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_rename_ground_ozone_minsk_observations_surface_ozone_minsk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observations',
            old_name='uvi_max_homel',
            new_name='max_uvi_homel',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uvi_max_minsk',
            new_name='max_uvi_minsk',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uvi_max_naroch',
            new_name='max_uvi_naroch',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='common_ozone_homel',
            new_name='total_ozone_homel',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='common_ozone_minsk',
            new_name='total_ozone_minsk',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='common_ozone_naroch',
            new_name='total_ozone_naroch',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uvi_homel',
            new_name='total_uvi_homel',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uvi_minsk',
            new_name='total_uvi_minsk',
        ),
        migrations.RenameField(
            model_name='observations',
            old_name='uvi_naroch',
            new_name='total_uvi_naroch',
        ),
    ]
