# Generated by Django 4.2.8 on 2023-12-26 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Предназначенин')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='main/devices', verbose_name='Главная фотография')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Прибор',
                'verbose_name_plural': 'Приборы',
                'ordering': ['-time_creation'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=455, null=True, verbose_name='Описание')),
                ('document', models.FileField(upload_to='main/documents', verbose_name='Файл документа')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
                'ordering': ['-time_creation'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('image_logo', models.ImageField(upload_to='main/news', verbose_name='Фотография')),
                ('body', models.TextField(verbose_name='Содержание новости')),
                ('published', models.DateField(verbose_name='Опубликовано для пользователя')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовано')], default='PB', max_length=2, verbose_name='Статус новости')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-time_creation'],
            },
        ),
        migrations.CreateModel(
            name='TechCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=70, verbose_name='Характеристика')),
                ('characteristic_value', models.CharField(max_length=20, verbose_name='Значение')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.devices', verbose_name='Прибор')),
            ],
            options={
                'verbose_name': 'Характеристика прибора',
                'verbose_name_plural': 'Характеристики прибора',
                'ordering': ['device', '-time_creation'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(upload_to='main/devices_gallery/', verbose_name='Фотография')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.devices', verbose_name='Прибор')),
            ],
            options={
                'verbose_name': 'Характеристика прибора',
                'verbose_name_plural': 'Характеристики прибора',
                'ordering': ['device', '-time_creation'],
            },
        ),
    ]
