# Generated by Django 4.2.8 on 2024-02-27 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_galleryimage_options_alter_devices_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic_name', models.CharField(max_length=70, verbose_name='Характеристика')),
                ('characteristic_name_ru', models.CharField(max_length=70, null=True, verbose_name='Характеристика')),
                ('characteristic_name_en', models.CharField(max_length=70, null=True, verbose_name='Характеристика')),
                ('characteristic_value', models.CharField(max_length=20, verbose_name='Значение')),
                ('characteristic_value_ru', models.CharField(max_length=20, null=True, verbose_name='Значение')),
                ('characteristic_value_en', models.CharField(max_length=20, null=True, verbose_name='Значение')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Характеристика прибора',
                'verbose_name_plural': 'Характеристики прибора',
                'ordering': ['device', '-time_creation'],
            },
        ),
        migrations.RemoveField(
            model_name='techcharacteristic',
            name='device',
        ),
        migrations.AddField(
            model_name='devices',
            name='description_en',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='devices',
            name='description_ru',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='devices',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='devices',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='devices',
            name='subtitle_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Предназначение'),
        ),
        migrations.AddField(
            model_name='devices',
            name='subtitle_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Предназначение'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_en',
            field=models.TextField(blank=True, max_length=455, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ru',
            field=models.TextField(blank=True, max_length=455, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Содержание новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.DeleteModel(
            name='TechCharacteristic',
        ),
        migrations.AddField(
            model_name='devicescharacteristic',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='main_app.devices', verbose_name='Прибор'),
        ),
    ]
