# Generated by Django 4.2.8 on 2024-02-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_devicescharacteristic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('image_logo', models.ImageField(upload_to='main/news', verbose_name='Фотография')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('published', models.DateField(verbose_name='Опубликовано для пользователя')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовано')], default='PB', max_length=2, verbose_name='Статус новости')),
                ('time_creation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в БД')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-time_creation'],
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_en',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
    ]
