# Generated by Django 4.2.8 on 2024-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_article_alter_news_body_alter_news_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
    ]
