# Generated by Django 4.2.8 on 2024-04-04 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_article_body_en_article_body_ru_article_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
