# Generated by Django 4.2.8 on 2024-04-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_be',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='devices',
            name='description_be',
            field=models.TextField(max_length=1500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='devices',
            name='name_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='devices',
            name='subtitle_be',
            field=models.CharField(max_length=200, null=True, verbose_name='Предназначение'),
        ),
        migrations.AddField(
            model_name='devicescharacteristic',
            name='characteristic_name_be',
            field=models.CharField(max_length=70, null=True, verbose_name='Характеристика'),
        ),
        migrations.AddField(
            model_name='devicescharacteristic',
            name='characteristic_value_be',
            field=models.CharField(max_length=20, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_be',
            field=models.TextField(blank=True, max_length=455, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='name_be',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='body_be',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_be',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
