# Generated by Django 4.2.8 on 2024-04-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_news_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('report_file', models.FileField(upload_to='observations/reports', verbose_name='Файл отчёта')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
            ],
            options={
                'verbose_name': 'Годовой отчёт',
                'verbose_name_plural': 'Годовые отчёты',
                'ordering': ['-year'],
            },
        ),
    ]
