# Generated by Django 4.2.8 on 2024-05-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_annualreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_be',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание'),
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='main/base_post_attach', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла (опционально)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_files', to='main_app.article')),
            ],
            options={
                'verbose_name': 'Файл к Статье',
                'verbose_name_plural': 'Файлы к Статье',
                'ordering': ['article'],
            },
        ),
    ]
