# Generated by Django 4.2.8 on 2024-05-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_article_body_alter_article_body_be_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefile',
            options={'ordering': ['article'], 'verbose_name': 'Файл к Статье', 'verbose_name_plural': 'Файлы к Статьям'},
        ),
        migrations.RemoveField(
            model_name='articlefile',
            name='name',
        ),
    ]
